name: tests
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 20]
    steps:
      - name: Setup TOR
        uses: tor-actions/setup-tor@main
        with:
          daemon: true
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
