name: tests
on: 
  push:
  pull_request:
  schedule:
    # Run once every 3 days:
    - cron: '0 21 */3 * *'
jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - name: Setup TOR
        uses: tor-actions/setup-tor@main
        with:
          daemon: true
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        env:
          TEST_LNBITS_CONFIG: '{"baseUrl":"${{ env.LNBITS_BASE_URL }}","adminKey":"${{ secrets.LNBITS_ADMIN_KEY }}"}'
          TEST_LNBITS_ADDINVOICE: '{"amount":50000}'
          TEST_LNBITS_GETBALANCE: '{}'
        run: npm test
